import type { Connector } from '../types'

export const INITIAL_CONNECTORS: Connector[] = [
  { id: 'youtube', name: 'YouTube', category: 'Social Media', color: '#ff0000', initials: 'YT', isConnected: false, requiresKey: true, keyPlaceholder: 'AIza...' },
  { id: 'tiktok', name: 'TikTok', category: 'Social Media', color: '#010101', initials: 'TK', isConnected: false, requiresKey: true, keyPlaceholder: 'TikTok API key' },
  { id: 'instagram', name: 'Instagram', category: 'Social Media', color: '#e1306c', initials: 'IG', isConnected: false, requiresKey: true, keyPlaceholder: 'Meta API token' },
  { id: 'twitter', name: 'Twitter / X', category: 'Social Media', color: '#1da1f2', initials: 'X', isConnected: false, requiresKey: true, keyPlaceholder: 'Bearer token' },
  { id: 'reddit', name: 'Reddit', category: 'Social Media', color: '#ff4500', initials: 'RD', isConnected: false, requiresKey: true, keyPlaceholder: 'Client secret' },
  { id: 'linkedin', name: 'LinkedIn', category: 'Social Media', color: '#0077b5', initials: 'LI', isConnected: false, requiresKey: true, keyPlaceholder: 'OAuth token' },
  {
    id: 'gworkspace',
    name: 'Google Workspace',
    category: 'Productivity',
    description: 'Powered by Google Workspace CLI — agents can manage Gmail, Drive, Docs, Sheets, and Calendar.',
    color: '#4285f4',
    initials: 'GW',
    isConnected: false,
    requiresKey: true,
    keyPlaceholder: 'OAuth2 credentials',
  },
  { id: 'notion', name: 'Notion', category: 'Productivity', color: '#000000', initials: 'NO', isConnected: false, requiresKey: true, keyPlaceholder: 'secret_...' },
  { id: 'airtable', name: 'Airtable', category: 'Productivity', color: '#18bfff', initials: 'AT', isConnected: false, requiresKey: true, keyPlaceholder: 'pat...' },
  { id: 'slack', name: 'Slack', category: 'Productivity', color: '#4a154b', initials: 'SL', isConnected: false, requiresKey: true, keyPlaceholder: 'xoxb-...' },
  { id: 'discord', name: 'Discord', category: 'Productivity', color: '#5865f2', initials: 'DC', isConnected: false, requiresKey: true, keyPlaceholder: 'Bot token' },
  { id: 'm365', name: 'Microsoft 365', category: 'Productivity', color: '#0078d4', initials: 'MS', isConnected: false, requiresKey: true, keyPlaceholder: 'Client secret' },
  { id: 'github', name: 'GitHub', category: 'Development', color: '#181717', initials: 'GH', isConnected: false, requiresKey: true, keyPlaceholder: 'ghp_...' },
  { id: 'vercel', name: 'Vercel', category: 'Development', color: '#000000', initials: 'VC', isConnected: false, requiresKey: true, keyPlaceholder: 'Vercel token' },
  { id: 'supabase', name: 'Supabase', category: 'Development', color: '#3ecf8e', initials: 'SB', isConnected: false, requiresKey: true, keyPlaceholder: 'Service role key' },
  { id: 'cloudflare', name: 'Cloudflare', category: 'Development', color: '#f6821f', initials: 'CF', isConnected: false, requiresKey: true, keyPlaceholder: 'API token' },
  { id: 'n8n', name: 'n8n', category: 'Automation', color: '#ea4b71', initials: 'N8', isConnected: false, requiresKey: true, keyPlaceholder: 'Webhook URL or API key' },
  { id: 'zapier', name: 'Zapier', category: 'Automation', color: '#ff4a00', initials: 'ZP', isConnected: false, requiresKey: true, keyPlaceholder: 'Zapier API key' },
  { id: 'make', name: 'Make', category: 'Automation', color: '#6d00cc', initials: 'MK', isConnected: false, requiresKey: true, keyPlaceholder: 'API key' },
  { id: 'pipedream', name: 'Pipedream', category: 'Automation', color: '#3cb371', initials: 'PD', isConnected: false, requiresKey: true, keyPlaceholder: 'API key' },
  { id: 'shopify', name: 'Shopify', category: 'E-commerce', color: '#96bf48', initials: 'SH', isConnected: false, requiresKey: true, keyPlaceholder: 'shpat_...' },
  { id: 'stripe', name: 'Stripe', category: 'E-commerce', color: '#635bff', initials: 'ST', isConnected: false, requiresKey: true, keyPlaceholder: 'sk_live_...' },
  { id: 'elevenlabs', name: 'ElevenLabs', category: 'Media & Creative', color: '#5a5a5a', initials: 'EL', isConnected: false, requiresKey: true, keyPlaceholder: 'xi_api_key' },
  { id: 'runway', name: 'Runway', category: 'Media & Creative', color: '#000000', initials: 'RW', isConnected: false, requiresKey: true, keyPlaceholder: 'API key' },
  { id: 'midjourney', name: 'Midjourney', category: 'Media & Creative', color: '#000000', initials: 'MJ', isConnected: false, requiresKey: true, keyPlaceholder: 'API key' },
  { id: 'stablediff', name: 'Stable Diffusion', category: 'Media & Creative', color: '#7f77dd', initials: 'SD', isConnected: false, requiresKey: true, keyPlaceholder: 'API key' },
  { id: 'gmail', name: 'Gmail', category: 'Communication', color: '#ea4335', initials: 'GM', isConnected: false, requiresKey: true, keyPlaceholder: 'OAuth2 credentials' },
  { id: 'telegram', name: 'Telegram', category: 'Communication', color: '#229ed9', initials: 'TG', isConnected: false, requiresKey: true, keyPlaceholder: 'Bot token' },
  { id: 'whatsapp', name: 'WhatsApp Business', category: 'Communication', color: '#25d366', initials: 'WA', isConnected: false, requiresKey: true, keyPlaceholder: 'Access token' },
]
