import { useState } from 'react'
import { ChevronDown, ChevronRight, FileCode, FolderOpen, File, CheckCircle, Circle, Loader, XCircle } from 'lucide-react'
import { Light as SyntaxHighlighter } from 'react-syntax-highlighter'
import ts from 'react-syntax-highlighter/dist/esm/languages/hljs/typescript'
import { atomOneDark } from 'react-syntax-highlighter/dist/esm/styles/hljs'
import { clsx } from 'clsx'
import { useAppStore } from '../../store/appStore'
import type { TaskStep } from '../../types'

SyntaxHighlighter.registerLanguage('typescript', ts)

const MOCK_CODE = `// Generated by Drodo Agent
import { describe, it, expect, beforeEach } from 'vitest'
import { createUser, loginUser, refreshToken } from '../auth'
import { db } from '../db/test-client'

describe('Authentication Module', () => {
  beforeEach(async () => {
    await db.clear()
  })

  it('should create a user and return JWT', async () => {
    const user = await createUser({
      email: 'test@example.com',
      password: 'secure-pass-123',
    })
    expect(user.token).toBeDefined()
    expect(user.id).toMatch(/^[0-9a-f-]{36}$/)
  })

  it('should reject invalid credentials', async () => {
    await expect(
      loginUser({ email: 'bad@email.com', password: 'wrong' })
    ).rejects.toThrow('Invalid credentials')
  })

  it('should refresh expired tokens', async () => {
    const { refreshToken: rt } = await createUser({ ... })
    const newToken = await refreshToken(rt)
    expect(newToken.accessToken).toBeDefined()
  })
})`

const FILE_TREE = [
  { name: 'src', type: 'folder', depth: 0, open: true },
  { name: 'auth', type: 'folder', depth: 1, open: true },
  { name: 'login.ts', type: 'file', depth: 2 },
  { name: 'middleware.ts', type: 'file', depth: 2 },
  { name: 'refresh.ts', type: 'file', depth: 2 },
  { name: 'tests', type: 'folder', depth: 1, open: true },
  { name: 'auth.test.ts', type: 'file', depth: 2, active: true },
  { name: 'db', type: 'folder', depth: 1, open: false },
]

function StepIcon({ status }: { status: TaskStep['status'] }) {
  if (status === 'complete') return <CheckCircle size={14} className="text-[#1d9e75] flex-shrink-0" />
  if (status === 'running') return <Loader size={14} className="text-[#7f77dd] flex-shrink-0 animate-spin" />
  if (status === 'error') return <XCircle size={14} className="text-[#e05050] flex-shrink-0" />
  return <Circle size={14} className="text-[#2a2a2e] flex-shrink-0" />
}

function Section({
  title, icon, children, defaultOpen = true
}: {
  title: string
  icon: React.ReactNode
  children: React.ReactNode
  defaultOpen?: boolean
}) {
  const [open, setOpen] = useState(defaultOpen)

  return (
    <div className="flex flex-col" style={{ borderBottom: '1px solid #2a2a2e' }}>
      <button
        onClick={() => setOpen(o => !o)}
        className="flex items-center gap-2 px-4 py-2.5 hover:bg-[#1c1c22] transition-colors"
        style={{ borderBottom: open ? '1px solid #2a2a2e' : 'none' }}
      >
        {open ? <ChevronDown size={12} className="text-[#6b6b78]" /> : <ChevronRight size={12} className="text-[#6b6b78]" />}
        {icon}
        <span className="text-xs font-semibold text-[#9898a8] uppercase tracking-wider">{title}</span>
      </button>
      {open && children}
    </div>
  )
}

export function RightPanel() {
  const taskSteps = useAppStore(s => s.taskSteps)

  return (
    <aside
      className="flex flex-col h-full flex-shrink-0 overflow-hidden"
      style={{
        width: 340,
        background: '#141418',
        borderLeft: '1px solid #2a2a2e',
      }}
    >
      {/* Live Output */}
      <Section
        title="Live Output"
        icon={<FileCode size={13} className="text-[#7f77dd]" />}
        defaultOpen={true}
      >
        <div className="overflow-auto" style={{ maxHeight: 220 }}>
          <SyntaxHighlighter
            language="typescript"
            style={atomOneDark}
            customStyle={{
              background: '#0d0d0f',
              margin: 0,
              padding: '12px 16px',
              fontSize: 11,
              lineHeight: 1.6,
            }}
            showLineNumbers
            lineNumberStyle={{ color: '#3a3a42', fontSize: 10 }}
          >
            {MOCK_CODE}
          </SyntaxHighlighter>
        </div>
      </Section>

      {/* File Tree */}
      <Section
        title="Files"
        icon={<FolderOpen size={13} className="text-[#d4a227]" />}
        defaultOpen={true}
      >
        <div className="py-1.5 overflow-auto" style={{ maxHeight: 180 }}>
          {FILE_TREE.map((item, i) => (
            <div
              key={i}
              className={clsx(
                'flex items-center gap-1.5 py-1 px-2 cursor-pointer hover:bg-[#1c1c22] transition-colors text-xs',
                (item as any).active ? 'text-[#e8e8ef] bg-[#7f77dd]/10' : 'text-[#9898a8]'
              )}
              style={{ paddingLeft: 12 + item.depth * 14 }}
            >
              {item.type === 'folder' ? (
                <>
                  {(item as any).open ? <ChevronDown size={11} className="text-[#6b6b78]" /> : <ChevronRight size={11} className="text-[#6b6b78]" />}
                  <FolderOpen size={13} className="text-[#d4a227]" />
                </>
              ) : (
                <>
                  <span className="w-3" />
                  <File size={13} className={(item as any).active ? 'text-[#7f77dd]' : 'text-[#6b6b78]'} />
                </>
              )}
              <span className={(item as any).active ? 'font-medium text-[#e8e8ef]' : ''}>{item.name}</span>
            </div>
          ))}
        </div>
      </Section>

      {/* Task Progress */}
      <Section
        title="Task Progress"
        icon={<CheckCircle size={13} className="text-[#1d9e75]" />}
        defaultOpen={true}
      >
        <div className="p-4 space-y-3 overflow-auto flex-1">
          {taskSteps.map((step, i) => (
            <div key={step.id} className="flex items-start gap-3">
              <div className="flex flex-col items-center">
                <StepIcon status={step.status} />
                {i < taskSteps.length - 1 && (
                  <div
                    className="w-px flex-1 mt-1"
                    style={{
                      height: 16,
                      background: step.status === 'complete' ? '#1d9e75' : '#2a2a2e',
                    }}
                  />
                )}
              </div>
              <span
                className={clsx(
                  'text-xs leading-tight pt-0.5',
                  step.status === 'complete' && 'text-[#9898a8] line-through',
                  step.status === 'running' && 'text-[#e8e8ef] font-medium',
                  step.status === 'pending' && 'text-[#6b6b78]',
                  step.status === 'error' && 'text-[#e05050]',
                )}
              >
                {step.label}
              </span>
            </div>
          ))}
        </div>
      </Section>
    </aside>
  )
}
